In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("llm.csv")

dataset

,model_name,model_slug,provider,provider_slug,aa_id,aa_intelligence_index,aa_coding_index,aa_math_index,composite_benchmark,mmlu_pro,...,arena_elo_ci95,arena_votes,parameter_count,release_year,is_open_source,intelligence_per_dollar,price_performance_ratio,elo_benchmark_blend,speed_per_dollar,scrape_date
0,GPT-5.4 (xhigh),gpt-5-4,OpenAI,openai,a89c4b28-2d8c-456e-88ea-255fb51fd2b6,57.2,57.3,NaN,63.40,NaN,...,8.0,5618.0,500.0,2026.0,False,10.17,33.53,80.68,15.94,2026-03-31
1,Gemini 3.1 Pro Preview,gemini-3-1-pro-preview,Google,google,bbd93ebe-80da-4594-bb19-61e69d0331df,57.2,55.5,NaN,65.90,NaN,...,6.0,15809.0,NaN,2026.0,False,12.71,38.66,96.02,26.71,2026-03-31
2,GPT-5.3 Codex (xhigh),gpt-5-3-codex,OpenAI,openai,59b5b14b-5365-4ee7-824a-18a8e6309644,54.0,53.1,NaN,61.53,NaN,...,NaN,NaN,500.0,2026.0,False,11.22,34.96,NaN,19.01,2026-03-31
3,"Claude Opus 4.6 (Adaptive Reasoning, Max Effort)",claude-opus-4-6-adaptive,Anthropic,anthropic,53c98840-47af-49aa-94e6-469fb17e9a1b,53.0,48.1,NaN,59.40,NaN,...,NaN,NaN,NaN,2025.0,False,5.30,24.77,NaN,6.06,2026-03-31
4,"Claude Sonnet 4.6 (Adaptive Reasoning, Max Eff...",claude-sonnet-4-6-adaptive,Anthropic,anthropic,df8d14e0-3997-4e4d-b4ad-9c047acc9c69,51.7,50.9,NaN,54.77,NaN,...,NaN,NaN,NaN,2025.0,False,8.62,28.14,NaN,12.90,2026-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,Cogito v2.1 (Reasoning),cogito-v2-1-reasoning,Deep Cogito,deepcogito,ea5d2c10-1051-437d-95c2-18d5e4d14ff3,NaN,24.8,72.7,56.50,0.849,...,NaN,NaN,NaN,NaN,True,NaN,69.67,NaN,74.03,2026-03-31
449,Mi:dm K 2.5 Pro Preview,midm-250-pro-rsnsft,Korea Telecom,korea-telecom,e0099b99-d368-4562-b0de-4016ea58af54,NaN,11.9,78.7,49.92,0.813,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,2026-03-31
450,GPT-4o Realtime (Dec '24),gpt-4o-realtime-dec-2024,OpenAI,openai,e2e9ddc3-8c2d-4bf5-a60a-83a1afe61034,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,200.0,2024.0,False,NaN,NaN,NaN,NaN,2026-03-31
451,GPT-3.5 Turbo (0613),gpt-3-5-turbo-0613,OpenAI,openai,8b1a70d1-e05f-426b-9122-023d4629ab47,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,2026-03-31
452,GPT-4o mini Realtime (Dec '24),gpt-4o-mini-realtime-dec-2024,OpenAI,openai,4343afb1-c928-44c9-92e2-68fa1195b6f5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,2025.0,False,NaN,NaN,NaN,NaN,2026-03-31

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   model_name                453 non-null    object
 1   model_slug                453 non-null    object
 2   provider                  453 non-null    object
 3   provider_slug             453 non-null    object
 4   aa_id                     453 non-null    object
 5   aa_intelligence_index     446 non-null    float64
 6   aa_coding_index           356 non-null    float64
 7   aa_math_index             268 non-null    float64
 8   composite_benchmark       433 non-null    float64
 9   mmlu_pro                  344 non-null    float64
 10  gpqa_diamond              424 non-null    float64
 11  humanitys_last_exam       420 non-null    float64
 12  livecodebench             342 non-null    float64
 13  scicode                   418 non-null    float64
 14  math_500                  201 non-null    float64
 15  aime_2025                 194 non-null    float64
 16  input_cost_usd_per_1m     315 non-null    float64
 17  output_cost_usd_per_1m    315 non-null    float64
 18  blended_cost_usd_per_1m   315 non-null    float64
 19  pricing_tier              453 non-null    object
 20  output_tokens_per_second  279 non-null    float64
 21  time_to_first_token_s     279 non-null    float64
 22  time_to_first_answer_s    279 non-null    float64
 23  chatbot_arena_elo         46 non-null     float64
 24  arena_elo_ci95            46 non-null     float64
 25  arena_votes               46 non-null     float64
 26  parameter_count           286 non-null    float64
 27  release_year              292 non-null    float64
 28  is_open_source            453 non-null    bool
 29  intelligence_per_dollar   297 non-null    float64
 30  price_performance_ratio   295 non-null    float64
 31  elo_benchmark_blend       46 non-null     float64
 32  speed_per_dollar          263 non-null    float64
 33  scrape_date               453 non-null    object
dtypes: bool(1), float64(26), object(7)
memory usage: 117.4+ KB

In [4]:
dataset.shape

(453, 34)

### Gawddamn i didnt know that we could use describe to actually pull off categorial values thats new 

#### step 1 : - loading the dataset , put .info() , put . shape , put .describe() if u wanna know more

In [5]:
dataset.describe(include='all')

,model_name,model_slug,provider,provider_slug,aa_id,aa_intelligence_index,aa_coding_index,aa_math_index,composite_benchmark,mmlu_pro,...,arena_elo_ci95,arena_votes,parameter_count,release_year,is_open_source,intelligence_per_dollar,price_performance_ratio,elo_benchmark_blend,speed_per_dollar,scrape_date
count,453,453,453,453,453,446.000000,356.000000,268.000000,433.000000,344.000000,...,46.000000,46.000000,286.000000,292.000000,453,297.000000,295.000000,46.00000,263.000000,453
unique,453,453,47,47,453,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,1
top,GPT-5.4 (xhigh),gpt-5-4,Alibaba,alibaba,a89c4b28-2d8c-456e-88ea-255fb51fd2b6,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,2026-03-31
freq,1,1,71,71,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,302,NaN,NaN,NaN,NaN,453
mean,NaN,NaN,NaN,NaN,NaN,21.241256,19.507022,50.358209,43.885358,0.695875,...,5.500000,28526.456522,168.665734,2025.304795,NaN,56.694377,132.377085,45.59087,652.151863,NaN
std,NaN,NaN,NaN,NaN,NaN,11.969957,12.756695,30.683282,15.960437,0.167493,...,1.929306,23704.998901,234.257631,0.853280,NaN,80.906908,140.634859,22.16947,2010.831957,NaN
min,NaN,NaN,NaN,NaN,NaN,4.700000,0.000000,0.000000,4.100000,0.055000,...,3.000000,2860.000000,0.600000,2023.000000,NaN,0.100000,9.730000,13.51000,0.790000,NaN
25%,NaN,NaN,NaN,NaN,NaN,12.000000,10.000000,23.350000,33.670000,0.633750,...,4.000000,11526.250000,9.250000,2025.000000,NaN,10.760000,42.620000,26.02250,38.315000,NaN
50%,NaN,NaN,NaN,NaN,NaN,17.950000,16.650000,52.800000,45.720000,0.752000,...,5.000000,20967.000000,49.000000,2026.000000,NaN,29.700000,82.940000,42.54500,119.170000,NaN
75%,NaN,NaN,NaN,NaN,NaN,28.475000,28.750000,79.475000,53.860000,0.814250,...,6.000000,38311.500000,235.000000,2026.000000,NaN,70.340000,174.565000,63.39500,473.960000,NaN
max,NaN,NaN,NaN,NaN,NaN,57.200000,57.300000,99.000000,95.400000,0.898000,...,11.000000,103891.000000,1200.000000,2026.000000,NaN,525.000000,1135.680000,96.02000,20735.850000,NaN

In [6]:
dataset.duplicated().sum() # calculating the sum of total duplicatesd

0

In [7]:
dataset.drop_duplicates() #dropping duplicates

,model_name,model_slug,provider,provider_slug,aa_id,aa_intelligence_index,aa_coding_index,aa_math_index,composite_benchmark,mmlu_pro,...,arena_elo_ci95,arena_votes,parameter_count,release_year,is_open_source,intelligence_per_dollar,price_performance_ratio,elo_benchmark_blend,speed_per_dollar,scrape_date
0,GPT-5.4 (xhigh),gpt-5-4,OpenAI,openai,a89c4b28-2d8c-456e-88ea-255fb51fd2b6,57.2,57.3,NaN,63.40,NaN,...,8.0,5618.0,500.0,2026.0,False,10.17,33.53,80.68,15.94,2026-03-31
1,Gemini 3.1 Pro Preview,gemini-3-1-pro-preview,Google,google,bbd93ebe-80da-4594-bb19-61e69d0331df,57.2,55.5,NaN,65.90,NaN,...,6.0,15809.0,NaN,2026.0,False,12.71,38.66,96.02,26.71,2026-03-31
2,GPT-5.3 Codex (xhigh),gpt-5-3-codex,OpenAI,openai,59b5b14b-5365-4ee7-824a-18a8e6309644,54.0,53.1,NaN,61.53,NaN,...,NaN,NaN,500.0,2026.0,False,11.22,34.96,NaN,19.01,2026-03-31
3,"Claude Opus 4.6 (Adaptive Reasoning, Max Effort)",claude-opus-4-6-adaptive,Anthropic,anthropic,53c98840-47af-49aa-94e6-469fb17e9a1b,53.0,48.1,NaN,59.40,NaN,...,NaN,NaN,NaN,2025.0,False,5.30,24.77,NaN,6.06,2026-03-31
4,"Claude Sonnet 4.6 (Adaptive Reasoning, Max Eff...",claude-sonnet-4-6-adaptive,Anthropic,anthropic,df8d14e0-3997-4e4d-b4ad-9c047acc9c69,51.7,50.9,NaN,54.77,NaN,...,NaN,NaN,NaN,2025.0,False,8.62,28.14,NaN,12.90,2026-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,Cogito v2.1 (Reasoning),cogito-v2-1-reasoning,Deep Cogito,deepcogito,ea5d2c10-1051-437d-95c2-18d5e4d14ff3,NaN,24.8,72.7,56.50,0.849,...,NaN,NaN,NaN,NaN,True,NaN,69.67,NaN,74.03,2026-03-31
449,Mi:dm K 2.5 Pro Preview,midm-250-pro-rsnsft,Korea Telecom,korea-telecom,e0099b99-d368-4562-b0de-4016ea58af54,NaN,11.9,78.7,49.92,0.813,...,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,NaN,2026-03-31
450,GPT-4o Realtime (Dec '24),gpt-4o-realtime-dec-2024,OpenAI,openai,e2e9ddc3-8c2d-4bf5-a60a-83a1afe61034,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,200.0,2024.0,False,NaN,NaN,NaN,NaN,2026-03-31
451,GPT-3.5 Turbo (0613),gpt-3-5-turbo-0613,OpenAI,openai,8b1a70d1-e05f-426b-9122-023d4629ab47,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,2026-03-31
452,GPT-4o mini Realtime (Dec '24),gpt-4o-mini-realtime-dec-2024,OpenAI,openai,4343afb1-c928-44c9-92e2-68fa1195b6f5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,2025.0,False,NaN,NaN,NaN,NaN,2026-03-31

In [8]:
dataset.isnull().sum() # checking for nulls

model_name                    0
model_slug                    0
provider                      0
provider_slug                 0
aa_id                         0
aa_intelligence_index         7
aa_coding_index              97
aa_math_index               185
composite_benchmark          20
mmlu_pro                    109
gpqa_diamond                 29
humanitys_last_exam          33
livecodebench               111
scicode                      35
math_500                    252
aime_2025                   259
input_cost_usd_per_1m       138
output_cost_usd_per_1m      138
blended_cost_usd_per_1m     138
pricing_tier                  0
output_tokens_per_second    174
time_to_first_token_s       174
time_to_first_answer_s      174
chatbot_arena_elo           407
arena_elo_ci95              407
arena_votes                 407
parameter_count             167
release_year                161
is_open_source                0
intelligence_per_dollar     156
price_performance_ratio     158
elo_benchmark_blend         407
speed_per_dollar            190
scrape_date                   0
dtype: int64

In [9]:
dataset.interpolate('ffill') # deprecated version lmao 
dataset.bfill()

/var/folders/20/y86c17l116d1rg_932q1sg8h0000gn/T/ipykernel_5290/3136478097.py:1: FutureWarning: DataFrame.interpolate with method=ffill is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dataset.interpolate('ffill') # deprecated version lmao

,model_name,model_slug,provider,provider_slug,aa_id,aa_intelligence_index,aa_coding_index,aa_math_index,composite_benchmark,mmlu_pro,...,arena_elo_ci95,arena_votes,parameter_count,release_year,is_open_source,intelligence_per_dollar,price_performance_ratio,elo_benchmark_blend,speed_per_dollar,scrape_date
0,GPT-5.4 (xhigh),gpt-5-4,OpenAI,openai,a89c4b28-2d8c-456e-88ea-255fb51fd2b6,57.2,57.3,99.0,63.40,0.874,...,8.0,5618.0,500.0,2026.0,False,10.17,33.53,80.68,15.94,2026-03-31
1,Gemini 3.1 Pro Preview,gemini-3-1-pro-preview,Google,google,bbd93ebe-80da-4594-bb19-61e69d0331df,57.2,55.5,99.0,65.90,0.874,...,6.0,15809.0,500.0,2026.0,False,12.71,38.66,96.02,26.71,2026-03-31
2,GPT-5.3 Codex (xhigh),gpt-5-3-codex,OpenAI,openai,59b5b14b-5365-4ee7-824a-18a8e6309644,54.0,53.1,99.0,61.53,0.874,...,5.0,23341.0,500.0,2026.0,False,11.22,34.96,60.29,19.01,2026-03-31
3,"Claude Opus 4.6 (Adaptive Reasoning, Max Effort)",claude-opus-4-6-adaptive,Anthropic,anthropic,53c98840-47af-49aa-94e6-469fb17e9a1b,53.0,48.1,99.0,59.40,0.874,...,5.0,23341.0,500.0,2025.0,False,5.30,24.77,60.29,6.06,2026-03-31
4,"Claude Sonnet 4.6 (Adaptive Reasoning, Max Eff...",claude-sonnet-4-6-adaptive,Anthropic,anthropic,df8d14e0-3997-4e4d-b4ad-9c047acc9c69,51.7,50.9,99.0,54.77,0.874,...,5.0,23341.0,500.0,2025.0,False,8.62,28.14,60.29,12.90,2026-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,Cogito v2.1 (Reasoning),cogito-v2-1-reasoning,Deep Cogito,deepcogito,ea5d2c10-1051-437d-95c2-18d5e4d14ff3,NaN,24.8,72.7,56.50,0.849,...,NaN,NaN,200.0,2024.0,True,NaN,69.67,NaN,74.03,2026-03-31
449,Mi:dm K 2.5 Pro Preview,midm-250-pro-rsnsft,Korea Telecom,korea-telecom,e0099b99-d368-4562-b0de-4016ea58af54,NaN,11.9,78.7,49.92,0.813,...,NaN,NaN,200.0,2024.0,True,NaN,NaN,NaN,NaN,2026-03-31
450,GPT-4o Realtime (Dec '24),gpt-4o-realtime-dec-2024,OpenAI,openai,e2e9ddc3-8c2d-4bf5-a60a-83a1afe61034,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,200.0,2024.0,False,NaN,NaN,NaN,NaN,2026-03-31
451,GPT-3.5 Turbo (0613),gpt-3-5-turbo-0613,OpenAI,openai,8b1a70d1-e05f-426b-9122-023d4629ab47,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,2025.0,False,NaN,NaN,NaN,NaN,2026-03-31
452,GPT-4o mini Realtime (Dec '24),gpt-4o-mini-realtime-dec-2024,OpenAI,openai,4343afb1-c928-44c9-92e2-68fa1195b6f5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,2025.0,False,NaN,NaN,NaN,NaN,2026-03-31

## There are few ways i could achieve this above with respect to filling na 

### 1. fillna(0) -> fill nulls with o 
### 2. fillna(dataset.mean) -> fills nulls with mean 
### 3. dataset.interpolate(method='linear') ( for numerical values ) (takes straight line between values )
### 4. dataset.interpolate(method='backward') ( takes backward numbers and inputs them )
### 5. dataset.interpolate(method='forward') (takes forward numbers and inputs them in null values )
### 6. dataset.interpolate(method = 'polynomial',order =2) ( curve fitting - time series models )

In [10]:
dataset.convert_dtypes(int) # this converts everything and doesnt have access to change one column 

#dataset['aa_intelligence_index']=dataset['aa_intelligence_index'].astype(int)  astype helps convert any column into specific datatype if its in the same format

,model_name,model_slug,provider,provider_slug,aa_id,aa_intelligence_index,aa_coding_index,aa_math_index,composite_benchmark,mmlu_pro,...,arena_elo_ci95,arena_votes,parameter_count,release_year,is_open_source,intelligence_per_dollar,price_performance_ratio,elo_benchmark_blend,speed_per_dollar,scrape_date
0,GPT-5.4 (xhigh),gpt-5-4,OpenAI,openai,a89c4b28-2d8c-456e-88ea-255fb51fd2b6,57.2,57.3,<NA>,63.4,<NA>,...,8,5618,500.0,2026,False,10.17,33.53,80.68,15.94,2026-03-31
1,Gemini 3.1 Pro Preview,gemini-3-1-pro-preview,Google,google,bbd93ebe-80da-4594-bb19-61e69d0331df,57.2,55.5,<NA>,65.9,<NA>,...,6,15809,<NA>,2026,False,12.71,38.66,96.02,26.71,2026-03-31
2,GPT-5.3 Codex (xhigh),gpt-5-3-codex,OpenAI,openai,59b5b14b-5365-4ee7-824a-18a8e6309644,54.0,53.1,<NA>,61.53,<NA>,...,<NA>,<NA>,500.0,2026,False,11.22,34.96,<NA>,19.01,2026-03-31
3,"Claude Opus 4.6 (Adaptive Reasoning, Max Effort)",claude-opus-4-6-adaptive,Anthropic,anthropic,53c98840-47af-49aa-94e6-469fb17e9a1b,53.0,48.1,<NA>,59.4,<NA>,...,<NA>,<NA>,<NA>,2025,False,5.3,24.77,<NA>,6.06,2026-03-31
4,"Claude Sonnet 4.6 (Adaptive Reasoning, Max Eff...",claude-sonnet-4-6-adaptive,Anthropic,anthropic,df8d14e0-3997-4e4d-b4ad-9c047acc9c69,51.7,50.9,<NA>,54.77,<NA>,...,<NA>,<NA>,<NA>,2025,False,8.62,28.14,<NA>,12.9,2026-03-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448,Cogito v2.1 (Reasoning),cogito-v2-1-reasoning,Deep Cogito,deepcogito,ea5d2c10-1051-437d-95c2-18d5e4d14ff3,<NA>,24.8,72.7,56.5,0.849,...,<NA>,<NA>,<NA>,<NA>,True,<NA>,69.67,<NA>,74.03,2026-03-31
449,Mi:dm K 2.5 Pro Preview,midm-250-pro-rsnsft,Korea Telecom,korea-telecom,e0099b99-d368-4562-b0de-4016ea58af54,<NA>,11.9,78.7,49.92,0.813,...,<NA>,<NA>,<NA>,<NA>,True,<NA>,<NA>,<NA>,<NA>,2026-03-31
450,GPT-4o Realtime (Dec '24),gpt-4o-realtime-dec-2024,OpenAI,openai,e2e9ddc3-8c2d-4bf5-a60a-83a1afe61034,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,200.0,2024,False,<NA>,<NA>,<NA>,<NA>,2026-03-31
451,GPT-3.5 Turbo (0613),gpt-3-5-turbo-0613,OpenAI,openai,8b1a70d1-e05f-426b-9122-023d4629ab47,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,False,<NA>,<NA>,<NA>,<NA>,2026-03-31
452,GPT-4o mini Realtime (Dec '24),gpt-4o-mini-realtime-dec-2024,OpenAI,openai,4343afb1-c928-44c9-92e2-68fa1195b6f5,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,8.0,2025,False,<NA>,<NA>,<NA>,<NA>,2026-03-31

### There are 2 ways to do typecasting 1. astype() , 2. convert_dtype()

In [11]:
dataset['scrape_date'] = dataset['scrape_date'].astype('date32[pyarrow]') # too complex lol i didnt know that

### There are 2 ways for date conversions -> 1. pd.to_datetime(dataset['']) this has the arrays and those lists will be used to access the data of the column so yeah 

### then comes .astype('date32[pyarrow]')

In [12]:


dataset['month'] = dataset['scrape_date'].dt.month
dataset['day'] = dataset['scrape_date'].dt.day
dataset['year'] = dataset['scrape_date'].dt.year

### thats the end of 19th may -> pandas has been real smooth till now but yeah gawddman this is fun , took no ai help lol except datetime cause understanding the concepts is neccessary and didnt know .dt was a thing 

### i might have used this but again not sure why i dont remember this so inshort pd.to_datetime , .astype , Interpolate (method = '') -> deprecated but still its the og thing which is good now its ffill(), bfill()

In [13]:
# back on thrusday , was having a migrane so couldnt continue 
df = pd.DataFrame({
    'region': ['North','South','North','South','North'],
    'sales': [100, 200, 150, 300, 120]
})
groups = df.groupby('region')
print(groups.mean())
print(groups.sum())

             sales
region
North   123.333333
South   250.000000
        sales
region
North     370
South     500

In [14]:
df1 = pd.DataFrame({'id': [1,2,3], 'name': ['Alice','Bob','Charlie']})
df2 = pd.DataFrame({'id': [1,2,4], 'sales': [100,200,300]})

bo = df1.merge(df2,how='outer')

print(bo)

   id     name  sales
0   1    Alice  100.0
1   2      Bob  200.0
2   3  Charlie    NaN
3   4      NaN  300.0

In [15]:
df = pd.DataFrame({
    'region': ['North','South','North','South','North'],
    'product': ['A','B','A','A','B'],
    'sales': [100,200,150,300,120]
})

df.groupby('region')['sales'].sum().idxmax

<bound method Series.idxmax of region
North    370
South    500
Name: sales, dtype: int64>

In [16]:
fd = df.groupby(['region','product'])['sales'].sum().idxmax()

print (fd)

('South', 'A')

In [17]:
df = pd.DataFrame({
    'region': ['North','South','North','South','North'],
    'product': ['A','B','A','A','B'],
    'sales': [100,200,150,300,120],
    'returns': [10,20,15,30,12]
})

fg = df.groupby('region')[['sales','returns']].sum()

print(fg)

        sales  returns
region
North     370       37
South     500       50

In [18]:
customers = pd.DataFrame({
    'id': [1,2,3,4],
    'name': ['Alice','Bob','Charlie','Dave']
})

orders = pd.DataFrame({
    'id': [1,2,5],
    'amount': [100,200,300]
})


oi = customers.merge(orders,how='inner')

print(oi)

   id   name  amount
0   1  Alice     100
1   2    Bob     200

In [41]:
df = pd.DataFrame({
    'sales': [100, 200, 150, 300, 120]
})

df['sales_doubled'] = df['sales'].apply(lambda x: x*2)

df['sales_category'] = df['sales'].apply(lambda x: 'high' if x>150  else "low")

df['summary'] = df['sales'].apply(lambda  x : 'sale:' + str(x))
print(df)

   sales  sales_doubled sales_category   summary
0    100            200            low  sale:100
1    200            400           high  sale:200
2    150            300            low  sale:150
3    300            600           high  sale:300
4    120            240            low  sale:120

### Here Lambda is a anonymous function that i can use in python in order define things in single line 

### x: x*2 , here x means the value inside of lambda , : x * 2 means what exactly are we trying to do with the value ( x * 2 ) makes it multiply thats about it and apply function just applies that to all columns 

### to define a new column , just take the data frame and define the [ column ] = df[ something ].apply(any function )

### to define a indepth function then u can write ( lambda x: 'high'if x>150 else 'low') this can be used in order to work around with defining the datasets with columns 

### new learning is lambda can also be used to concat strings , apply ( lambda x: 'sale : ' + str(x) -> here u are converting integers to strings and then concating them )

In [46]:
df = pd.DataFrame({
    'color': ['red','blue','red','green','blue']

})

pd.get_dummies(df['color'] ,dtype=int)

   blue  green  red
0     0      0    1
1     1      0    0
2     0      0    1
3     0      1    0
4     1      0    0

## One Huge Differentiation That Needs to Be Done Is Trying to ensure that while working with Ordinal and if u dont have anything except pandas then go with map () function , it maps functions towards whatever value u associate with 

## Now get_dummies can be used in order to generate values which dont have any coherent value , like words so get_dummies assigns values to it as those words have no structure of variables 

### if u are trying to use map () then do it this way  , df[ 'levels' ].map({'low' : 1 , "high" :2}) remember to use {} when defining levels or ordinals in ml it would be onehotencoding